# Generated by Django 3.0.2 on 2020-02-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('permission_action', models.CharField(max_length=256)),
                ('remark', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuthCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('remark', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('remark', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('create_time', models.DateTimeField()),
                ('enable', models.BooleanField(default=True)),
                ('remark', models.CharField(max_length=256)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Role')),
            ],
        ),
        migrations.CreateModel(
            name='RoleAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Auth')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Role')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='authorities',
            field=models.ManyToManyField(through='flowmeter.RoleAuth', to='flowmeter.Auth'),
        ),
        migrations.AddField(
            model_name='auth',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.AuthCategory'),
        ),
    ]
