# Generated by Django 2.2 on 2020-02-16 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User'),
            preserve_default=False,
        ),
    ]
