# Generated by Django 3.0.2 on 2020-02-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enable',
            field=models.CharField(default='enable', max_length=16),
        ),
    ]
