# Generated by Django 2.2 on 2020-02-16 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0002_meter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OprLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opr_time', models.DateTimeField()),
                ('state', models.CharField(max_length=16)),
                ('opr_name', models.CharField(max_length=64)),
                ('opr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opr_time', models.DateTimeField()),
                ('state', models.CharField(max_length=16)),
                ('opr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlarmLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opr_time', models.DateTimeField()),
                ('state', models.CharField(max_length=16)),
                ('alarm_type', models.CharField(max_length=64)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Meter')),
                ('meter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_user', to='flowmeter.User')),
                ('opr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
