# Generated by Django 2.2 on 2020-02-16 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0003_alarmlog_loginlog_oprlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmlog',
            name='meter_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_alarm', to='flowmeter.User'),
        ),
    ]
