# Generated by Django 3.0.2 on 2020-02-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0003_auto_20200205_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enable',
            new_name='state',
        ),
    ]
