# Generated by Django 2.2 on 2020-02-16 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0004_auto_20200216_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_type', models.CharField(max_length=16)),
                ('address', models.IntegerField(null=True)),
                ('dtu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Dtu')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='valve',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Valve'),
            preserve_default=False,
        ),
    ]
