# Generated by Django 3.0.2 on 2020-02-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0004_auto_20200205_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='', max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('fid', models.IntegerField(default=-1)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Auth')),
            ],
        ),
    ]
