# Generated by Django 3.0.2 on 2020-02-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0005_navigationbar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navigationbar',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='navigationbar',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='authcategory',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
