# Generated by Django 2.2 on 2020-02-16 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0005_auto_20200216_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='valve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Valve'),
        ),
    ]
