# Generated by Django 2.2 on 2020-02-16 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0006_auto_20200216_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmlog',
            name='state',
        ),
    ]
