# Generated by Django 2.2 on 2020-02-16 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0008_remove_alarmlog_meter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oprlog',
            old_name='opr_name',
            new_name='opr_type',
        ),
    ]
