# Generated by Django 2.2 on 2020-02-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0009_auto_20200216_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oprlog',
            options={'ordering': ['opr_time']},
        ),
        migrations.AddField(
            model_name='dtu',
            name='dtu_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oprlog',
            name='meter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Meter'),
            preserve_default=False,
        ),
    ]
