# Generated by Django 2.2 on 2020-02-17 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0011_auto_20200217_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafield',
            name='frame_format',
        ),
        migrations.RemoveField(
            model_name='dtu',
            name='protocol',
        ),
    ]
