# Generated by Django 2.2 on 2020-02-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0012_auto_20200217_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Protocol',
        ),
    ]
