# Generated by Django 2.2 on 2020-02-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0013_delete_protocol'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.IntegerField()),
                ('const_data', models.IntegerField(null=True)),
                ('remark', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
