# Generated by Django 2.2 on 2020-02-17 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0014_controlregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationbar',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Auth'),
        ),
    ]
