# Generated by Django 2.2 on 2020-02-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0015_auto_20200217_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlregister',
            name='opr_type',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
