# Generated by Django 2.2 on 2020-02-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0016_controlregister_opr_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlregister',
            name='opr_type',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
