# Generated by Django 2.2 on 2020-02-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0017_auto_20200218_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='field_name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
