# Generated by Django 2.2 on 2020-02-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0018_datafield_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valve_state', models.CharField(default='known', max_length=8)),
                ('recharge_state', models.CharField(default='known', max_length=8)),
                ('battery_pressure_state', models.CharField(default='known', max_length=8)),
                ('valve_error_flag', models.IntegerField(default=-1)),
                ('owe_state', models.IntegerField(default=-1)),
                ('sensor_error_flag', models.IntegerField(default=-1)),
                ('state', models.CharField(default='known', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='meter',
            name='battery_pressure_state',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='owe_state',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='recharge_state',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='sensor_error_flag',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='valve_error_flag',
        ),
        migrations.RemoveField(
            model_name='meter',
            name='valve_state',
        ),
        migrations.AlterField(
            model_name='meter',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.MeterState'),
        ),
    ]
