# Generated by Django 2.2 on 2020-02-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0019_auto_20200218_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlregister',
            old_name='address',
            new_name='field_val',
        ),
    ]
