# Generated by Django 2.2 on 2020-02-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0020_auto_20200220_1150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meter',
            unique_together={('dtu', 'address')},
        ),
    ]
