# Generated by Django 2.2 on 2020-02-21 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0021_auto_20200221_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='dturegion',
            name='used_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meter',
            name='flow_rate',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='flow_ratio',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='last_update_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='power',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='remark',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='state',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.MeterState'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='surplus_gas',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='surplus_gas_limits',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='temperature',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='total_flow',
            field=models.FloatField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='meter',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='version',
            field=models.FloatField(default=-1, null=True),
        ),
    ]
