# Generated by Django 2.2 on 2020-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0022_auto_20200221_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtu',
            name='dtu_no',
            field=models.IntegerField(unique=True),
        ),
    ]
