# Generated by Django 2.2 on 2020-02-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0025_auto_20200221_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterstate',
            old_name='state',
            new_name='online_state',
        ),
    ]
