# Generated by Django 2.2 on 2020-02-22 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0026_auto_20200221_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dturegion',
            name='manufacturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User'),
        ),
    ]
