# Generated by Django 2.2 on 2020-02-23 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0027_auto_20200222_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='user',
        ),
        migrations.AddField(
            model_name='dtu',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User'),
        ),
    ]
