# Generated by Django 3.0.2 on 2020-03-11 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0030_auto_20200224_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dturegion',
            options={'ordering': ['manufacturer', 'left']},
        ),
        migrations.AlterField(
            model_name='valve',
            name='dtu',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Dtu'),
        ),
    ]
