# Generated by Django 3.0.2 on 2020-03-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0031_auto_20200311_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='valve',
            name='valve_dtu',
            field=models.ForeignKey(db_column='dtu_valve_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dtu_valve', to='flowmeter.Dtu'),
        ),
    ]
