# Generated by Django 3.0.2 on 2020-03-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0032_valve_valve_dtu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='valve',
        ),
    ]
