# Generated by Django 3.0.2 on 2020-03-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0036_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configure',
            name='val',
            field=models.CharField(max_length=256),
        ),
    ]
