# Generated by Django 3.0.2 on 2020-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0037_auto_20200313_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='val',
            field=models.CharField(max_length=256),
        ),
    ]
