# Generated by Django 3.0.2 on 2020-03-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0039_oprlog_val'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterstate',
            name='online_state',
        ),
    ]
