# Generated by Django 3.0.2 on 2020-03-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0040_remove_meterstate_online_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meter',
            name='state',
        ),
        migrations.AddField(
            model_name='meterstate',
            name='meter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Meter'),
        ),
        migrations.AddField(
            model_name='valve',
            name='meter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Meter'),
        ),
        migrations.AlterField(
            model_name='valve',
            name='dtu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Dtu'),
        ),
        migrations.AlterUniqueTogether(
            name='valve',
            unique_together={('dtu', 'address')},
        ),
        migrations.RemoveField(
            model_name='valve',
            name='valve_dtu',
        ),
        migrations.RemoveField(
            model_name='valve',
            name='valve_type',
        ),
    ]
