# Generated by Django 3.0.2 on 2020-03-19 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0041_auto_20200317_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opr_time', models.DateTimeField()),
                ('action', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=16)),
                ('opr_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
