# Generated by Django 3.0.2 on 2020-03-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0042_auto_20200319_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemlog',
            old_name='action',
            new_name='action_type',
        ),
    ]
