# Generated by Django 3.0.2 on 2020-03-19 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0043_auto_20200319_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmlog',
            name='opr_user',
        ),
    ]
