# Generated by Django 3.0.2 on 2020-03-19 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0044_remove_alarmlog_opr_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='msg',
            field=models.CharField(default='', max_length=128),
        ),
    ]
