# Generated by Django 3.0.2 on 2020-03-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0045_systemlog_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmlog',
            name='state',
            field=models.CharField(default='unread', max_length=16),
        ),
    ]
