# Generated by Django 3.0.2 on 2020-03-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0046_alarmlog_state'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='alarmlog',
            index=models.Index(fields=['state'], name='state_index'),
        ),
    ]
