# Generated by Django 3.0.2 on 2020-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0048_auto_20200322_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmlogreader',
            name='unique_flag',
            field=models.CharField(default=0, max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
