# Generated by Django 3.0.2 on 2020-03-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0049_alarmlogreader_unique_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterHistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=256)),
                ('time', models.DateField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowmeter.Meter')),
            ],
        ),
    ]
