# Generated by Django 3.0.2 on 2020-03-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0050_auto_20200329_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterhistorydata',
            name='data',
            field=models.FloatField(max_length=256),
        ),
    ]
