# Generated by Django 3.0.2 on 2020-03-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0050_meterhistorydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmlogreader',
            name='unique_flag',
            field=models.CharField(max_length=128),
        ),
    ]
