# Generated by Django 3.0.2 on 2020-04-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0051_auto_20200329_2308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='valve',
            unique_together=set(),
        ),
    ]
