# Generated by Django 3.0.2 on 2020-05-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0052_auto_20200403_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oprlog',
            options={'ordering': ['opr_time', 'meter__id']},
        ),
        migrations.AddField(
            model_name='dtu',
            name='online_state',
            field=models.CharField(default='offline', max_length=16),
        ),
        migrations.AddField(
            model_name='oprlog',
            name='dtu_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='oprlog',
            name='show_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterIndexTogether(
            name='oprlog',
            index_together={('state', 'dtu_no')},
        ),
    ]
