# Generated by Django 3.0.2 on 2020-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0053_auto_20200503_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnExecutedOpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opr_time', models.FloatField()),
                ('dtu_no', models.IntegerField()),
                ('log_id', models.IntegerField()),
                ('address', models.IntegerField()),
                ('opr_type', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['dtu_no', 'address', 'opr_type'],
            },
        ),
        migrations.CreateModel(
            name='WaitOpr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opr_time', models.FloatField()),
                ('dtu_no', models.IntegerField()),
                ('log_id', models.IntegerField()),
                ('address', models.IntegerField()),
                ('opr_type', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['dtu_no', 'address', 'opr_type'],
            },
        ),
        migrations.AlterIndexTogether(
            name='oprlog',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='oprlog',
            name='dtu_no',
        ),
        migrations.RemoveField(
            model_name='oprlog',
            name='show_flag',
        ),
    ]
