# Generated by Django 3.0.2 on 2020-05-03 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0054_auto_20200503_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unexecutedopr',
            name='log_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waitopr',
            name='log_id',
            field=models.IntegerField(null=True),
        ),
    ]
