# Generated by Django 3.0.2 on 2020-05-03 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0057_auto_20200503_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unexecutedopr',
            options={'ordering': ['opr_time']},
        ),
        migrations.AlterModelOptions(
            name='waitopr',
            options={'ordering': ['opr_time']},
        ),
    ]
