# Generated by Django 3.0.2 on 2020-05-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0058_auto_20200503_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='unexecutedopr',
            name='val',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='waitopr',
            name='val',
            field=models.FloatField(null=True),
        ),
    ]
