# Generated by Django 3.0.2 on 2020-05-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowmeter', '0060_auto_20200504_0022'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='waitopr',
            index_together={('dtu_no', 'address', 'opr_type', 'opr_time')},
        ),
    ]
